version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: shopmate-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: shopmate_ai
    volumes:
      - mongo-data:/data/db
    networks:
      - shopmate-network

  redis:
    image: redis:7-alpine
    container_name: shopmate-redis
    ports:
      - "6379:6379"
    networks:
      - shopmate-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: shopmate-server
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: shopmate_ai
      CLIENT_URL: http://localhost:3000
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./server/src:/app/server/src
    networks:
      - shopmate-network
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: shopmate-client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      REACT_APP_ENV: development
    depends_on:
      - server
    networks:
      - shopmate-network

volumes:
  mongo-data:

networks:
  shopmate-network:
    driver: bridge
