name: UAT - Upload to Git to Vercel

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies (Server)
      run: |
        cd server
        npm install

    - name: Install dependencies (Client)
      run: |
        cd client
        npm install

    - name: Build Server
      run: |
        cd server
        npm run build

    - name: Build Client
      run: |
        cd client
        npm run build

    - name: Run Tests (Server)
      run: |
        cd server
        npm run test -- --passWithNoTests

    - name: Deploy to Vercel (Server)
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_SERVER }}
        working-directory: ./server
        production: ${{ github.ref == 'refs/heads/main' }}

    - name: Deploy to Vercel (Client)
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_CLIENT }}
        working-directory: ./client
        production: ${{ github.ref == 'refs/heads/main' }}

    - name: Comment PR with deployment URLs
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ Deployment preview ready!\n- Server: https://shopmate-server-dev.vercel.app\n- Client: https://shopmate-client-dev.vercel.app'
          })
